version: 1.0
provider:
  name: openfaas
  gateway: faas1:8080
functions:
  nsfw:
    lang: dockerfile
    handler: ./openfaas-opennsfw
    image: spekulatius/openfaas-opennsfw:latest
    environment:
      read_timeout: 120
      write_timeout: 120
      exec_timeout: 120
